### ISSUE TITLE
mbedls: Linux Subsystem error

### ISSUE THREAD

**Issue by jainvikas8** [ARMmbed/mbed-os-tools#178]
### Running mbedls on subsystem (Linux - Ubunutu) on Windows returns an error (udev)

```
Name: mbed-os-tools
Version: 0.0.8
Summary: The tools to build, test, and work with Mbed OS
Home-page: https://github.com/ARMmbed/mbed-os-tools
Author: Jimmy Brisson, Brian Daniels
Author-email: jimmy.brisson@arm.com, brian.daniels@arm.com
License: Apache-2.0
Location: /home/vikkat01/.local/lib/python2.7/site-packages
Requires: appdirs, fasteners, PrettyTable, colorama, lockfile, requests, intelhex, junit-xml, future, PySerial, six
```

mbed - Version - 1.10.0

Step to reproduce would to install Ubuntu Sub-system on the machine and run mbedls.

```
ERROR:mbedls.lstools_linux:Could not get disk devices by id. This could be because your Linux distribution does not use udev, or does not create /dev/disk/by-id symlinks. Please submit an issue to github.com/armmbed/mbed-ls.
ERROR:mbedls.lstools_linux:Could not get serial devices by id. This could be because your Linux distribution does not use udev, or does not create /dev/serial/by-id symlinks. Please submit an issue to github.com/armmbed/mbed-ls.
Traceback (most recent call last):
  File "/home/vikkat01/.local/bin/mbedls", line 11, in <module>
    sys.exit(mbedls_main())
  File "/home/vikkat01/.local/lib/python2.7/site-packages/mbed_lstools/main.py", line 194, in mbedls_main
    ret_code = args.command(mbeds, args)
  File "/home/vikkat01/.local/lib/python2.7/site-packages/mbed_lstools/main.py", line 60, in print_table
    return print_mbeds(mbeds, args, False)
  File "/home/vikkat01/.local/lib/python2.7/site-packages/mbed_lstools/main.py", line 47, in print_mbeds
    devices = mbeds.list_mbeds(unique_names=True, read_details_txt=True)
  File "/home/vikkat01/.local/lib/python2.7/site-packages/mbed_os_tools/detect/lstools_base.py", line 136, in list_mbeds
    candidates = list(self.find_candidates())
  File "/home/vikkat01/.local/lib/python2.7/site-packages/mbed_os_tools/detect/linux.py", line 54, in find_candidates
    usb_info = self._sysfs_block_devices(disk_ids.values())
  File "/home/vikkat01/.local/lib/python2.7/site-packages/mbed_os_tools/detect/linux.py", line 121, in _sysfs_block_devices
    sysfs_block_devices = set(os.listdir(SYSFS_BLOCK_DEVICE_PATH))
OSError: [Errno 2] No such file or directory: '/sys/class/block'
```

I'm trying this for the first time on Linux Sub-system (Ubuntu) running on Windows 10. Other commands don't fail except this one when trying to list the devices connected.

Any suggestions? To make it work? Idea is to use Linux Subsystem main system.

On the other hand Windows mbed CLI works fine.

```
> mbedls
| platform_name       | platform_name_unique   | mount_point | serial_port | target_id                | daplink_version |
|---------------------|------------------------|-------------|-------------|--------------------------|-----------------|
| DISCO_L475VG_IOT01A | DISCO_L475VG_IOT01A[0] | D:          | COM4        | 076402216E20657F5164F326 | 0221            |```

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1210*

**Comment by LDong-Arm** [comment]
As of now, Linux Subsystem on Windows doesn't support access to physical devices - see https://github.com/Microsoft/WSL/issues/689

From my understanding, there might be limited support for serial and binding a partition to the subsystem, but this is probably not enough for mbedls or mbed test, etc.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
