### ISSUE TITLE
"mbedgt --retry-count=0" doesn't work

### ISSUE THREAD

**Issue by VeijoPesonen** [ARMmbed/mbed-os-tools#214]
### Description
```
-@ubuntu:~/ws/mbed-os$ mbedgt --test-spec BUILD/tests/CY8CPROTO_062_4343W/GCC_ARM/test_spec.json --retry-count=0
[1580213373.42][root]Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
[1580213373.44][root]Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
mbedgt: greentea test automation tool ver. 1.7.4
mbedgt: test specification file 'BUILD/tests/CY8CPROTO_062_4343W/GCC_ARM/test_spec.json' (specified with --test-spec option)
mbedgt: using 'BUILD/tests/CY8CPROTO_062_4343W/GCC_ARM/test_spec.json' from current directory!
mbedgt: detecting connected mbed-enabled devices...
[1580213373.56][mbedls.lstools_base]MBED with target id '190113018b0f0b15028b0f0b00000000000000002e127069' is connected, but not mounted. Use the '-u' flag to include it in the list.
mbedgt: detected 5 devices
mbedgt: processing target 'CY8CPROTO_062_4343W' toolchain 'GCC_ARM' compatible platforms... (note: switch set to --parallel 1)
mbedgt: running 25 tests for platform 'CY8CPROTO_062_4343W' and toolchain 'GCC_ARM'
mbedgt: mbed-host-test-runner: started
mbedgt: ['mbedhtrun', '-m', 'CY8CPROTO_062_4343W', '-p', '/dev/ttyACM0:9600', '-f', '"BUILD/tests/CY8CPROTO_062_4343W/GCC_ARM/features/storage/TESTS/blockdevice/heap_block_device/heap_block_device.hex"', '-d', '/media/-/DAPLINK3', '-c', 'default', '-t', '190113018b131713028b131700000000000000002e127069', '-r', 'default', '-C', '4', '--sync', '5', '-P', '60'] failed after 0 count
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/-/.virtualenvs/mbed-os-python3/lib/python3.6/site-packages/mbed_greentea/mbed_greentea_cli.py", line 432, in run_test_thread
    verbose=verbose)
  File "/home/-/.virtualenvs/mbed-os-python3/lib/python3.6/site-packages/mbed_greentea/mbed_test_api.py", line 246, in run_host_test
    testcase_duration = end_time - start_time   # Test case duration from reset to {end}
UnboundLocalError: local variable 'end_time' referenced before assignment

mbedgt: could not generate test report
mbedgt: completed in 0.16 sec
mbedgt: exited with code 1
```

`mbed-greentea (1.7.4) - INSTALLED: 1.7.4 (latest)`
`Python 3.6.9`

Another issue: the help tells that retry count is by default 0 but in reality it is one. That's why I ended up trying to set the retry count explicitly to zero.

`mbedgt -h | grep retry`
`  --retry-count=RETRY_COUNT retry count for individual test failure. By default, there is no retry` 

### Issue request type

    [ ] Question
    [ ] Enhancement
    [X] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-548*
